# Generated by Django 2.2.6 on 2019-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='content',
            field=models.TextField(),
        ),
    ]
